name: TOC Generator

on:
  push:
    paths:
      - 'README.md'

jobs:
  generateTOC:
    name: TOC Generator
    uses: Cysharp/Actions/.github/workflows/toc-generator.yaml@main
    with:
      TOC_TITLE: "## Table of Contents"
    secrets: inherit
